<script>
  import { createEventDispatcher, onMount } from 'svelte';
  import { pb } from '../services/pocketbase';
  import { fade } from 'svelte/transition';
  import { ensureWalletExists } from '../services/WalletService';

  export let user;
  export let walletBalance;

  const dispatch = createEventDispatcher();

  let loading = true;
  let error = '';

  onMount(async () => {
    if (pb.authStore.isValid) {
      try {
        const userId = pb.authStore.model.id;
        const wallet = await ensureWalletExists(userId);
        walletBalance = wallet.token_balance;
        user = pb.authStore.model;
      } catch (err) {
        console.error('Error fetching wallet:', err);
        error = 'Unable to fetch wallet information. Please try refreshing the page.';
      } finally {
        loading = false;
      }
    } else {
      loading = false;
    }
  });

  function close() {
    dispatch('close');
  }

  async function logout() {
    pb.authStore.clear();
    window.location.href = '/login';
  }

  function getRoleLabel(role) {
    switch (role) {
      case 'DataProvider':
        return 'Data Provider';
      case 'Customer':
        return 'Customer';
      case 'Admin':
        return 'Administrator';
      default:
        return role;
    }
  }

  function getAvatarUrl(user) {
    if (user?.avatar) {
      return pb.files.getUrl(user, user.avatar);
    }
    // Use DiceBear Avatars API for autogenerated avatar
    const hash = encodeURIComponent(user.id || user.email || 'default');
    return `https://api.dicebear.com/6.x/identicon/svg?seed=${hash}`;
  }
</script>

<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50" transition:fade>
  <div class="bg-white rounded-lg p-8 max-w-md w-full max-h-90vh overflow-y-auto">
    <h2 class="text-2xl font-bold mb-4">User Profile</h2>
    {#if loading}
      <p>Loading user information...</p>
    {:else if error}
      <p class="text-red-500">{error}</p>
    {:else}
      <div class="flex items-center mb-4">
        <img 
          src={getAvatarUrl(user)} 
          alt="User avatar" 
          class="w-20 h-20 rounded-full mr-4"
        />
        <div>
          <p class="font-semibold text-xl">{user.name}</p>
          <p class="text-gray-600">{user.email}</p>
        </div>
      </div>
      
      <p class="mb-4">Role: {getRoleLabel(user.role)}</p>
      <p class="mb-4 flex items-center">
        Wallet Balance: 
        <img src="/grably-icon.png" alt="Grably icon" class="inline-block w-4 h-4 ml-2 mr-1" />
        ${walletBalance.toFixed(2)}
      </p>
      
      <button 
        on:click={logout}
        class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 mr-2"
      >
        Logout
      </button>
      <button 
        on:click={close}
        class="bg-gray-300 text-gray-800 px-4 py-2 rounded hover:bg-gray-400"
      >
        Close
      </button>
    {/if}
  </div>
</div>

<style>
  .max-h-90vh {
    max-height: 90vh;
  }
</style>